/**
 * Publications page — dynamically renders from data/publications.json
 * Generated by tools/fetch_scholar.py from Google Scholar.
 */

(function () {
  const DATA_PATH = '../data/publications.json';

  async function init() {
    const container = document.getElementById('publications-list');
    if (!container) return;

    try {
      const resp = await fetch(DATA_PATH);
      const data = await resp.json();

      // Render Google Scholar link
      const statsEl = document.getElementById('scholar-stats');
      if (statsEl && data.author) {
        const a = data.author;
        statsEl.innerHTML = `
          <a href="https://scholar.google.com/citations?user=${a.scholar_id}&hl=en" target="_blank" rel="noopener" style="color:var(--accent-blue)">google scholar ↗</a>
        `;
      }

      // Group by year
      const byYear = {};
      for (const pub of data.publications) {
        const y = pub.year || 'Unknown';
        if (!byYear[y]) byYear[y] = [];
        byYear[y].push(pub);
      }

      // Sort years descending
      const years = Object.keys(byYear).sort((a, b) => b - a);

      let html = '';
      for (const year of years) {
        html += `<div class="pub-year">${year}</div>\n`;
        for (const pub of byYear[year]) {
          const links = [];
          if (pub.url) {
            const isArxiv = pub.url.includes('arxiv');
            links.push(`<a class="pub-link" href="${pub.url}" target="_blank" rel="noopener">${isArxiv ? 'arxiv' : 'paper'}</a>`);
          }
          if (pub.eprint && !pub.url?.includes('arxiv')) {
            links.push(`<a class="pub-link" href="https://arxiv.org/abs/${pub.eprint}" target="_blank" rel="noopener">arxiv</a>`);
          }
          const citationsBadge = pub.citations > 0
            ? `<span style="color:var(--text-muted);font-size:var(--font-size-xs);margin-left:var(--space-sm);">cited: ${pub.citations}</span>`
            : '';

          html += `
            <div class="pub-item">
              <div class="pub-title">${pub.title}</div>
              <div class="pub-authors">${pub.authors}</div>
              ${pub.venue ? `<div class="pub-venue">${pub.venue}</div>` : ''}
              <div class="pub-links">
                ${links.join('\n                ')}
                ${citationsBadge}
              </div>
            </div>\n`;
        }
      }

      container.innerHTML = html;

      // Show last fetched date
      if (data.fetched) {
        const fetchedEl = document.getElementById('last-fetched');
        if (fetchedEl) {
          const d = new Date(data.fetched);
          fetchedEl.textContent = `last synced from google scholar: ${d.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' })}`;
        }
      }

    } catch (e) {
      container.innerHTML = '<p style="color:var(--text-muted)">Failed to load publications.</p>';
    }
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
